/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTable;

/**
 *
 * @author h
 */
public class PAtient_Ticket_List extends javax.swing.JFrame {

    /**
     * Creates new form PAtient_Ticket_List
     */
    public PAtient_Ticket_List() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    
    
    public void ChangeColor(JPanel hover, Color random)
    {
        hover.setBackground(random);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patient_list_panel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_ticket_list = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        closeMax_body = new javax.swing.JPanel();
        close_panel = new javax.swing.JPanel();
        close_white = new javax.swing.JLabel();
        maximise = new javax.swing.JPanel();
        maximise_label = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        search_Id = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        searchRegDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patient_list_panel.setBackground(new java.awt.Color(0, 51, 51));
        patient_list_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        patient_list_panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                patient_list_panelComponentShown(evt);
            }
        });
        patient_list_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_ticket_list.setBackground(new java.awt.Color(0, 51, 51));
        table_ticket_list.setForeground(new java.awt.Color(255, 255, 255));
        table_ticket_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Full Name", "Father Name", "Age", "Gender", "Contact", "Doctor Name", "Address", "Patient Illness", "Registration Date"
            }
        ));
        table_ticket_list.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                table_ticket_listComponentShown(evt);
            }
        });
        jScrollPane6.setViewportView(table_ticket_list);

        patient_list_panel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1130, 530));

        header.setBackground(new java.awt.Color(5, 10, 46));
        header.setPreferredSize(new java.awt.Dimension(875, 43));
        header.setLayout(new java.awt.BorderLayout());

        closeMax_body.setBackground(new java.awt.Color(5, 10, 46));
        closeMax_body.setPreferredSize(new java.awt.Dimension(84, 54));

        close_panel.setBackground(new java.awt.Color(5, 10, 46));
        close_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_panelMouseExited(evt);
            }
        });
        close_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_white.setBackground(new java.awt.Color(5, 10, 46));
        close_white.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/close_white1.png"))); // NOI18N
        close_white.setPreferredSize(new java.awt.Dimension(16, 20));
        close_panel.add(close_white, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 39, 42));

        maximise.setBackground(new java.awt.Color(5, 10, 46));
        maximise.setPreferredSize(new java.awt.Dimension(100, 42));
        maximise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximiseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximiseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximiseMouseExited(evt);
            }
        });
        maximise.setLayout(new java.awt.BorderLayout());

        maximise_label.setBackground(new java.awt.Color(5, 10, 46));
        maximise_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximise_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/maximize.png"))); // NOI18N
        maximise.add(maximise_label, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout closeMax_bodyLayout = new javax.swing.GroupLayout(closeMax_body);
        closeMax_body.setLayout(closeMax_bodyLayout);
        closeMax_bodyLayout.setHorizontalGroup(
            closeMax_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeMax_bodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(maximise, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        closeMax_bodyLayout.setVerticalGroup(
            closeMax_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeMax_bodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(closeMax_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maximise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        header.add(closeMax_body, java.awt.BorderLayout.LINE_END);

        patient_list_panel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 1126, 40));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        patient_list_panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 50));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        patient_list_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 190, 50));

        search_Id.setBackground(new java.awt.Color(0, 51, 51));
        search_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_IdActionPerformed(evt);
            }
        });
        search_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_IdKeyReleased(evt);
            }
        });
        patient_list_panel.add(search_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 200, 40));

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        patient_list_panel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, 50));

        searchRegDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchRegDateMouseClicked(evt);
            }
        });
        patient_list_panel.add(searchRegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 190, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("Search Id");
        patient_list_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 90, 40));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        patient_list_panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 130, 40));

        getContentPane().add(patient_list_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patient_list_panelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_patient_list_panelComponentShown

    }//GEN-LAST:event_patient_list_panelComponentShown

    private void table_ticket_listComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_table_ticket_listComponentShown
      
        try {
            String Driver = "com.mysql.jdbc.Driver";
            String URL = "jdbc:mysql://localhost:3306/medical";
            Class.forName(Driver);
            Connection Conn = DriverManager.getConnection(URL, "root", "");
            //Statement S = Conn.createStatement();
          
            String query = "select *from employee_ticket";
            PreparedStatement pst = Conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) table_ticket_list.getModel();
            //model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new String[]
                    {
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                        rs.getString(8),
                        rs.getString(9),
                        rs.getString(10)

                    });
                }
            } catch (Exception e) {
            }
    }//GEN-LAST:event_table_ticket_listComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
      try {
            String Driver = "com.mysql.jdbc.Driver";
            String URL = "jdbc:mysql://localhost:3306/medical";
            Class.forName(Driver);
            Connection Conn = DriverManager.getConnection(URL, "root", "");
            //Statement S = Conn.createStatement();
          
            String query = "select *from patient_receipt";
            PreparedStatement pst = Conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) table_ticket_list.getModel();
            //model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new String[]
                    {
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                        rs.getString(8),
                        rs.getString(9),
                        rs.getString(10)

                    });
                }
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void close_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseClicked

        System.exit(0);
    }//GEN-LAST:event_close_panelMouseClicked

    private void close_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseEntered
        ChangeColor(close_panel,new Color(210, 43, 43));
    }//GEN-LAST:event_close_panelMouseEntered

    private void close_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseExited
        ChangeColor(close_panel,new Color(5,10,46));
    }//GEN-LAST:event_close_panelMouseExited

    private void maximiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximiseMouseClicked

        if(this.getExtendedState()!= Admin_Panels.MAXIMIZED_BOTH)
        {

            this.setExtendedState(Admin_Panels.MAXIMIZED_BOTH);
        }
        else
        {
            this.setExtendedState(Admin_Panels.NORMAL);
        }
    }//GEN-LAST:event_maximiseMouseClicked

    private void maximiseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximiseMouseEntered
        ChangeColor(maximise,new Color(102,102,102));
    }//GEN-LAST:event_maximiseMouseEntered

    private void maximiseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximiseMouseExited
        ChangeColor(maximise,new Color(5,10,46));
    }//GEN-LAST:event_maximiseMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
       ///new employee_panel1().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void search_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_IdActionPerformed
       
    }//GEN-LAST:event_search_IdActionPerformed

    private void search_IdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_IdKeyReleased
        try {
            
            String sea= search_Id.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
            Statement st = (Statement)con.createStatement();
            /////String query = "SELECT 'Name','Contact','Bld','Address','LastDonation','Image' FROM 'don'";
            String query = "select * from patient_receipt where Patient_Id like '"+sea+"'";
            //String query = "select * from employee_ticket where Patient_Id ='+sea+'";
            ResultSet rs = st.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) table_ticket_list.getModel();
            //model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new String[]
                    {
                        rs.getString("Patient_Id"),
                        rs.getString("Full_Name"),
                        rs.getString("Father_Name"),
                        rs.getString("Age"),
                        rs.getString("Gender"),
                        rs.getString("Contact"),
                        rs.getString("Doctor_Name"),
                        rs.getString("Address"),
                        rs.getString("Patient_Illness"),
                        rs.getString("Registration_Date")

                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_search_IdKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       dispose();
       new PAtient_Ticket_List().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchRegDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchRegDateMouseClicked
        try {
//            Date date = new Date(searchRegDate.getDate().getTime());
//            
//            String pattern  = "dd-MM-yyyy";
//            DateFormat formatter = new SimpleDateFormat(pattern);
//            
//            //java.sql.Date d = (java.sql.Date) searchRegDate.getDate();
//            java.util.Date d = (java.util.Date) searchRegDate.getDate();
//            //java.util.Date
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//            String s = sdf.format(d);
                SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
                String B_date = dFormat.format(searchRegDate.getDate());
            
            String sea= search_Id.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
            Statement st = (Statement)con.createStatement();
            /////String query = "SELECT 'Name','Contact','Bld','Address','LastDonation','Image' FROM 'don'";
            String query = "select * from employee_ticket where Registration_Date like '"+B_date+"' ";
            ResultSet rs = st.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) table_ticket_list.getModel();
            //model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new String[]
                    {
                        rs.getString("Patient_Id"),
                        rs.getString("Full_Name"),
                        rs.getString("Father_Name"),
                        rs.getString("Age"),
                        rs.getString("Gender"),
                        rs.getString("Contact"),
                        rs.getString("Doctor_Name"),
                        rs.getString("Address"),
                        rs.getString("Patient_Illness"),
                        rs.getString("Registration_Date")

                    });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_searchRegDateMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        MessageFormat header = new MessageFormat("I am jOBAYE3D");
        MessageFormat foter = new MessageFormat("Daffodil International University");
        try {
            table_ticket_list.print(JTable.PrintMode.NORMAL,header,foter);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAtient_Ticket_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAtient_Ticket_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAtient_Ticket_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAtient_Ticket_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAtient_Ticket_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closeMax_body;
    private javax.swing.JPanel close_panel;
    private javax.swing.JLabel close_white;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel maximise;
    private javax.swing.JLabel maximise_label;
    private javax.swing.JPanel patient_list_panel;
    private com.toedter.calendar.JDateChooser searchRegDate;
    private javax.swing.JTextField search_Id;
    private javax.swing.JTable table_ticket_list;
    // End of variables declaration//GEN-END:variables
}
