/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;


public class Employee_View extends javax.swing.JFrame implements Runnable{

    int hour,min,sec;
    int Emp_ID;
    private String gender;
    private String status;
    
    
    public Employee_View() {
        initComponents();
        
        Thread t = new Thread(this);
        t.start();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        emp_id.requestFocus();
       
        SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
       
        
        //un editavle text field
        
        txt_emp_full_name.setEditable(false);
        txt_emp_father_name.setEditable(false);
        txt_emp_mother_name.setEditable(false);
        emp_bd.setEnabled(false);
        txt_emp_status.setEditable(false);
        txt_emp_contact1.setEditable(false);
        txt_emp_contact2.setEditable(false);
        txt_emp_gen.setEditable(false);
        lbl_image.setEnabled(false);
        txt_emp_dep.setEditable(false);
        txt_emp_address.setEditable(false);
        
    }
    
    //patient increase id
    
    
    
    
    //ImagePath
    String ImgPath = null;
    
    //Resize Image 
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        if(imagePath !=null)
        {
            myImage = new ImageIcon(imagePath);
        }
        else
        {
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ticket_profile = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        download = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txt_emp_contact2 = new javax.swing.JTextField();
        txt_emp_dep = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emp_bd = new com.toedter.calendar.JDateChooser();
        combo_emp_age = new javax.swing.JComboBox<>();
        lbl_image = new javax.swing.JLabel();
        txt_emp_contact1 = new javax.swing.JTextField();
        txt_emp_gen = new javax.swing.JTextField();
        txt_emp_status = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_emp_address = new javax.swing.JTextField();
        txt_emp_full_name = new javax.swing.JTextField();
        txtExtra = new javax.swing.JTextField();
        txt_emp_father_name = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_emp_mother_name = new javax.swing.JTextField();
        Error_Id = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticket_profile.setBackground(new java.awt.Color(46, 64, 83));
        ticket_profile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ticket_profileComponentShown(evt);
            }
        });
        ticket_profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(93, 109, 126));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employye Profile Update");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(657, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ticket_profile.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jPanel4.setBackground(new java.awt.Color(46, 64, 83));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        download.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        download.setForeground(new java.awt.Color(255, 255, 255));
        download.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        download.setText("Download");
        download.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        download.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        download.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadMouseClicked(evt);
            }
        });
        jPanel4.add(download, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 40));

        reset.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        jPanel4.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 50));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Closwe");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 50));

        ticket_profile.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 240, 450));

        jPanel6.setBackground(new java.awt.Color(46, 64, 83));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_emp_contact2.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_contact2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_contact2.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_contact2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_contact2.setText("Contact 2");
        txt_emp_contact2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_contact2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_contact2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_contact2FocusLost(evt);
            }
        });
        jPanel6.add(txt_emp_contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 200, 36));

        txt_emp_dep.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_dep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_dep.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_dep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_dep.setText("Department");
        txt_emp_dep.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_dep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_depFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_depFocusLost(evt);
            }
        });
        jPanel6.add(txt_emp_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 200, 36));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Birthday Date  :");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, -1));

        emp_bd.setBackground(new java.awt.Color(46, 64, 83));
        emp_bd.setForeground(new java.awt.Color(255, 255, 255));
        emp_bd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emp_bd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_bdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emp_bdMouseEntered(evt);
            }
        });
        jPanel6.add(emp_bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 40));

        combo_emp_age.setBackground(new java.awt.Color(46, 64, 83));
        combo_emp_age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combo_emp_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                   Age", "10 Day", "1 Month", "2 Month", "3 Month", "4 Month", "5 Month", "6 Month", "7 Month", "8 Month", "9 Month", "10 Month", "01 Year", "02 Year", "03Year", "04 Year", "05 Year", "06 Year", "07 Year", "08 Year", "09 Year", "10 Year", "12 Year", "13 Year", "14 Year", "15 Year", "16 Year", "17 Year", "18 Year", "19 Year", "20 Year", "21 Year", "22 Year", "23 Year", "24 Year", "25 Year", "26 Year", "27 Year", "28 Year", "29 Year", "30 Year", "31 Year", "32 Year", "33 Year", "34 Year", "35 Year", "36 Year", "37 Year", "38 Year", "39 Year", "40 Year", "41 Year", "42 Year", "43 Year", "44 Year", "45 Year", "46 Year", "47 Year", "48 Year", "49 Year", "50 Year", "51 Year", "52 Year", "53 Year", "54 Year", "55 Year", "56 Year", "57 Year", "58 Year", "59 Year", "60 Year", "61 Year", "62 Year", "63 Year", "64 Year", "65 Year", "66 Year", "67 Year", "68 Year", "69 Year", "70 Year", "71 Year", "72 Year", "73 Year", "74 Year", "75 Year", "76 Year", "77 Year", "78 Year", "79 Year", "80 Year" }));
        combo_emp_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_emp_ageActionPerformed(evt);
            }
        });
        jPanel6.add(combo_emp_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, 40));

        lbl_image.setBackground(new java.awt.Color(0, 51, 51));
        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/insert.png"))); // NOI18N
        lbl_image.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        lbl_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imageMouseClicked(evt);
            }
        });
        jPanel6.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 220, 230));

        txt_emp_contact1.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_contact1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_contact1.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_contact1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_contact1.setText("Contact 1");
        txt_emp_contact1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_contact1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_contact1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_contact1FocusLost(evt);
            }
        });
        jPanel6.add(txt_emp_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, 36));

        txt_emp_gen.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_gen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_gen.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_gen.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_gen.setText("Gender");
        txt_emp_gen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_gen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_genFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_genFocusLost(evt);
            }
        });
        jPanel6.add(txt_emp_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 319, 200, 36));

        txt_emp_status.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_status.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_status.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_status.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_status.setText("Relational Status");
        txt_emp_status.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_statusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_statusFocusLost(evt);
            }
        });
        jPanel6.add(txt_emp_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 200, 36));

        ticket_profile.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 670, 450));

        jPanel7.setBackground(new java.awt.Color(46, 64, 83));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_emp_address.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_address.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_address.setText("Address");
        txt_emp_address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_addressFocusLost(evt);
            }
        });
        jPanel7.add(txt_emp_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 93, 180, 36));

        txt_emp_full_name.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_full_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_full_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_full_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_full_name.setText("Full Name");
        txt_emp_full_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_full_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_full_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_full_nameFocusLost(evt);
            }
        });
        txt_emp_full_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_full_nameKeyReleased(evt);
            }
        });
        jPanel7.add(txt_emp_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 13, 180, 36));

        txtExtra.setBackground(new java.awt.Color(46, 64, 83));
        txtExtra.setBorder(null);
        jPanel7.add(txtExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 97, 20, -1));

        txt_emp_father_name.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_father_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_father_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_father_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_father_name.setText("Father Name");
        txt_emp_father_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_father_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_father_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_father_nameFocusLost(evt);
            }
        });
        txt_emp_father_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_father_nameKeyReleased(evt);
            }
        });
        jPanel7.add(txt_emp_father_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 13, 180, 36));

        jPanel5.setBackground(new java.awt.Color(46, 64, 88));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee/search icon.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 12, -1, 40));

        emp_id.setBackground(new java.awt.Color(46, 64, 83));
        emp_id.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        emp_id.setForeground(new java.awt.Color(204, 204, 255));
        emp_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emp_idKeyReleased(evt);
            }
        });
        jPanel5.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Id");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 1, 280, 76));

        txt_emp_mother_name.setBackground(new java.awt.Color(46, 64, 83));
        txt_emp_mother_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_emp_mother_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_mother_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emp_mother_name.setText("Mother Name");
        txt_emp_mother_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_emp_mother_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_mother_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_mother_nameFocusLost(evt);
            }
        });
        jPanel7.add(txt_emp_mother_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 93, 180, 36));
        jPanel7.add(Error_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 142, 27));

        Time.setBackground(new java.awt.Color(46, 64, 83));
        Time.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        Time.setForeground(new java.awt.Color(0, 204, 204));
        Time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Time.setText("jLabel5");
        jPanel7.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 150, 30));

        Date.setBackground(new java.awt.Color(46, 64, 83));
        Date.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(0, 204, 204));
        Date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Date.setText("jLabel5");
        jPanel7.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 150, 30));

        jButton1.setText("download");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        ticket_profile.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 987, 160));

        jPanel1.add(ticket_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 986, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 684));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticket_profileComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ticket_profileComponentShown

    }//GEN-LAST:event_ticket_profileComponentShown

    private void txt_emp_contact2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_contact2FocusGained
        if (txt_emp_contact2.getText().equals("Contact 2")) {
            txt_emp_contact2.setText("");
            txt_emp_contact2.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_contact2FocusGained

    private void txt_emp_contact2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_contact2FocusLost
        if (txt_emp_contact2.getText().equals("")) {
            txt_emp_contact2.setText("Contact 2");
            txt_emp_contact2.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_contact2FocusLost

    private void txt_emp_depFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_depFocusGained
        if (txt_emp_dep.getText().equals("Department")) {
            txt_emp_dep.setText("");
            txt_emp_dep.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_depFocusGained

    private void txt_emp_depFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_depFocusLost
        if (txt_emp_dep.getText().equals("")) {
            txt_emp_dep.setText("Department");
            txt_emp_dep.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_depFocusLost

    private void emp_bdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_bdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_bdMouseClicked

    private void emp_bdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_bdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_bdMouseEntered

    private void combo_emp_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_emp_ageActionPerformed

        String age = (String) combo_emp_age.getSelectedItem();
        if("                   Age".equals(age))
        {
            //JOptionPane.showMessageDialog(null,"Sorry! This is not selecte!");
            JOptionPane.showMessageDialog(null, "Sorry! This is not select!",
                "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_combo_emp_ageActionPerformed

    private void lbl_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imageMouseClicked

        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (Exception e) {
        }
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_image.setIcon(ResizeImage(path,null));
            ImgPath=path;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry! No File Selected");
        }
    }//GEN-LAST:event_lbl_imageMouseClicked

    private void txt_emp_contact1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_contact1FocusGained
        if (txt_emp_contact1.getText().equals("Contact 1")) {
            txt_emp_contact1.setText("");
            txt_emp_contact1.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_contact1FocusGained

    private void txt_emp_contact1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_contact1FocusLost
      if (txt_emp_contact1.getText().equals("")) {
            txt_emp_contact1.setText("Contact 1");
            txt_emp_contact1.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_contact1FocusLost

    private void txt_emp_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_addressFocusGained
        if (txt_emp_address.getText().equals("Address")) {
            txt_emp_address.setText("");
            txt_emp_address.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_addressFocusGained

    private void txt_emp_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_addressFocusLost
        if (txt_emp_address.getText().equals("")) {
            txt_emp_address.setText("Address");
            txt_emp_address.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_addressFocusLost

    private void txt_emp_full_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_full_nameFocusGained
        if (txt_emp_full_name.getText().equals("Full Name")) {
            txt_emp_full_name.setText("");
            txt_emp_full_name.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_full_nameFocusGained

    private void txt_emp_full_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_full_nameFocusLost
        if (txt_emp_full_name.getText().equals("")) {
            txt_emp_full_name.setText("Full Name");
            txt_emp_full_name.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_full_nameFocusLost

    private void txt_emp_full_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_full_nameKeyReleased

        //txtSubject.setText(txt_patient_full_name.getText());
    }//GEN-LAST:event_txt_emp_full_nameKeyReleased

    private void txt_emp_father_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_father_nameFocusGained
        if (txt_emp_father_name.getText().equals("Father Name")) {
            txt_emp_father_name.setText("");
            txt_emp_father_name.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_father_nameFocusGained

    private void txt_emp_father_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_father_nameFocusLost
        if (txt_emp_father_name.getText().equals("")) {
            txt_emp_father_name.setText("Father Name");
            txt_emp_father_name.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_father_nameFocusLost

    private void txt_emp_father_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_father_nameKeyReleased

    }//GEN-LAST:event_txt_emp_father_nameKeyReleased

    private void txt_emp_mother_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_mother_nameFocusGained
        if (txt_emp_mother_name.getText().equals("Mother Name")) {
            txt_emp_mother_name.setText("");
            txt_emp_mother_name.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_mother_nameFocusGained

    private void txt_emp_mother_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_mother_nameFocusLost
        if (txt_emp_mother_name.getText().equals("")) {
            txt_emp_mother_name.setText("Mother Name");
            txt_emp_mother_name.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_mother_nameFocusLost

    private void emp_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_idKeyReleased
       String search = emp_id.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
            Statement st = (Statement)con.createStatement();
            String query = "select *from employee where Id='"+search+"'";
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next())
            {
//                String s1 = rs.getString(1); //id 
//                String s2 = rs.getString(2); //Full NAme
//                String s3 = rs.getString(3); //F Name
//                String s4 = rs.getString(4); //Mother Name
//                Date s5 = rs.getDate(5); // Birthday
//                String s6 = rs.getString(6); //status              
//                String s7 = rs.getString(7); //contact
//                String s9 = rs.getString(9); // Department
//                String s10 = rs.getString(10);// address
//                String s12 = rs.getString(11); //gendwer
//                //String s11 = rs.getString(10);
                
               
                String s2 = rs.getString("FullName"); //Full NAme
                txt_emp_full_name.setText(s2);
                
                String s3 = rs.getString("FatherName"); //F Name
                txt_emp_father_name.setText(s3);
                
                String s4 = rs.getString("MotherName"); //Mother Name
                txt_emp_mother_name.setText(s4);
                
                Date s5 = rs.getDate("Birthday"); // Birthday
                emp_bd.setDate(s5);
                 
                String s6 = rs.getString("Status"); //status
                txt_emp_status.setText(s6);
                 
                String s7 = rs.getString("Contact_1"); //contact
                txt_emp_contact1.setText(s7);
                
                String s8 = rs.getString("Contact_2"); //contact
                txt_emp_contact2.setText(s8);
                
                lbl_image.setIcon(ResizeImage(null, rs.getBytes(8)));
                                
                String s10 = rs.getString("Department"); // Department
                txt_emp_dep.setText(s10);
                
                String s11 = rs.getString("Address");// address
                txt_emp_address.setText(s11);
                
                String s12 = rs.getString("Gender"); //gendwer
                txt_emp_gen.setText(s12);
                //String s11 = rs.getString(10);
               
                
                
                
                
               
               
                
                
                
                Error_Id.setText("*Id match");
                Error_Id.setForeground(Color.GREEN);
               
                txt_emp_full_name.setEditable(true);
                txt_emp_father_name.setEditable(true);
                txt_emp_mother_name.setEditable(true);
                emp_bd.setEnabled(false);
                txt_emp_status.setEditable(true);
                txt_emp_contact1.setEditable(true);
                txt_emp_contact2.setEditable(true);
                txt_emp_gen.setEditable(false);
                lbl_image.setEnabled(true);
                txt_emp_dep.setEditable(true);
                txt_emp_address.setEditable(true);
                
               
//               txtId.setEditable(false);
//               txtFname.setEditable(true);
//               txtYear.setEditable(false);
//               txtMonth.setEditable(false);
//               txtDate.setEditable(false);
//               txtOcuu.setEditable(true);
//               txtContact.setEditable(true);
//               txtBlood.setEditable(false);
//               txtAddress.setEditable(true);
//               txtLastDate.setEditable(true);
//               
//               Browse.setVisible(true);
//               ErrorId.setText(null);
               
            }
            else
            {
               
                Error_Id.setVisible(true);
                Error_Id.setText("*Sorry! Id doesn't match");
            }
          
           con.close();
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
        
        
        
 
    }//GEN-LAST:event_emp_idKeyReleased

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        dispose();
        new Employee_View().setVisible(true);
    }//GEN-LAST:event_resetMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void downloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadMouseClicked
       
                String E_id= emp_id.getText();
                String E_FullName= txt_emp_full_name.getText();
                String E_Fname= txt_emp_father_name.getText();
                String E_Mname= txt_emp_mother_name.getText();
                
                String E_contact1= txt_emp_contact1.getText();
                String E_contact2= txt_emp_contact2.getText();
                SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
                String B_date = dFormat.format(emp_bd.getDate());
                //String P_Doctor_name = (String) combo_patient_doctor_name.getSelectedItem();
                String E_address= txt_emp_address.getText();
                String E_dep= txt_emp_dep.getText();
                String E_gen = txt_emp_gen.getText();
                String E_sta = txt_emp_status.getText();
                String Age = (String) combo_emp_age.getSelectedItem();
                String path="D:\\";
                
                
                try {
                    com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            
//                    SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
//                    String B_date = dFormat.format(emp_bd.getDate());
//                    String Age = (String) combo_emp_age.getSelectedItem();
                    
                    PdfWriter.getInstance(doc, new FileOutputStream(path +""+E_FullName+ " "+".pdf"));
                    doc.open();
                    
                    String title="                        Daffodil Medical Systems\n\n";
                    Paragraph paragrph1 = new Paragraph(title);
                    doc.add(paragrph1);
                    
                    String Content = "Time  :- " + Time.getText() + "\nDate  :- " + Date.getText();
                    Paragraph paragrph2 = new Paragraph(Content);
                    doc.add(paragrph2);
                    
                    String Employee_Id = "Employee Id  :- "+emp_id.getText();
                    Paragraph paragrph3 = new Paragraph(Employee_Id);
                    doc.add(paragrph3);
                    
//                    String content="Time :- "+Time.getText() +"\nDate  :- "+Date_label.getText()+"\n\nEmploye Id  :-  "+emp_id+"Employee Name :- "+E_FullName+"Employee Father Name :- "+E_Fname +"Employee Mother Name :- "+E_Mname+
//                            "Birthday Date :- "+B_date +"Contact Number1 :- "+E_contact1 +"Contact Number2 :- "+E_contact2 +"Age      :-  "+Age +"Address   :-  "+E_address +"Department  :- "+E_dep
//                            +"Gender  :- "+E_gen  +"Relational Status : -"+E_sta;
//                    
//                    Paragraph paragrph2 = new Paragraph(content);
//                    doc.add(paragrph2);
                    
                    JOptionPane.showMessageDialog(null,"Done");
                    doc.close();
                    //PdfPTable tbl = new PdfPTable(3);
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_downloadMouseClicked

    private void txt_emp_genFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_genFocusGained
       if (txt_emp_gen.getText().equals("Gender")) {
            txt_emp_gen.setText("");
            txt_emp_gen.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_genFocusGained

    private void txt_emp_genFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_genFocusLost
        if (txt_emp_gen.getText().equals("")) {
            txt_emp_gen.setText("Gender");
            txt_emp_gen.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_genFocusLost

    private void txt_emp_statusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_statusFocusGained
        if (txt_emp_status.getText().equals("Relational Status")) {
            txt_emp_status.setText("");
            txt_emp_status.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_statusFocusGained

    private void txt_emp_statusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_statusFocusLost
        if (txt_emp_status.getText().equals("")) {
            txt_emp_status.setText("Relational Status");
            txt_emp_status.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_statusFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        try {
            //String path="D:\\Pdf";
            String id=emp_id.getText();
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(""+id +".pdf"));
            
            document.open();
            
            String title="Daffodil Medical System";
            document.add(new Paragraph(title,FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED)));
            document.add(new Paragraph("--------------------------------------------------------------"));
            
            String time_date="Time   :-  "+Time  +"Date  :-  "+Date;
            document.add(new Paragraph(time_date));
            
            JOptionPane.showMessageDialog(null, "Done");
            document.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Error_Id;
    private javax.swing.JLabel Time;
    private javax.swing.JComboBox<String> combo_emp_age;
    private javax.swing.JLabel download;
    private com.toedter.calendar.JDateChooser emp_bd;
    private javax.swing.JTextField emp_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel reset;
    private javax.swing.JPanel ticket_profile;
    private javax.swing.JTextField txtExtra;
    private javax.swing.JTextField txt_emp_address;
    private javax.swing.JTextField txt_emp_contact1;
    private javax.swing.JTextField txt_emp_contact2;
    private javax.swing.JTextField txt_emp_dep;
    private javax.swing.JTextField txt_emp_father_name;
    private javax.swing.JTextField txt_emp_full_name;
    private javax.swing.JTextField txt_emp_gen;
    private javax.swing.JTextField txt_emp_mother_name;
    private javax.swing.JTextField txt_emp_status;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        while(true)
        {
            Calendar cal = Calendar.getInstance();
            hour = cal.get(Calendar.HOUR_OF_DAY);
            min = cal.get(Calendar.MINUTE);
            sec = cal.get(Calendar.SECOND);
            
            
            SimpleDateFormat sdf12 = new SimpleDateFormat("hh:mm:ss aa");
           
            java.util.Date dat =  cal.getTime();
            String time12 = sdf12.format(dat);
            Time.setText(time12);
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy");
            
            Date.setText(sdf.format(dat));
            
            
        }
    }
    
}
