package Admin;

import medical.*;
import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.prefs.Preferences;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author h
 */
public class All_Login extends javax.swing.JFrame {
    
    public Preferences pref = Preferences.userRoot().node("Rememberme");
    public Preferences prefDoctor = Preferences.userRoot().node("Rememberme");
    public Preferences prerfEmployee = Preferences.userRoot().node("Rememberme");
    
    public All_Login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
      
        
        //remember me demployee username and password
        String usrE = null;
        usrE = prerfEmployee.get("Email", usrE);
        //username.setText(usr);
        txt_emp_id.setText(usrE);
        String pssE = null;
        pssE = pref.get("Password",pssE);
        txt_password_emp.setText(pssE);      
        
    }
    
  
    
     
    
     /////employee remember me password
      public void saveemailpass(String Email,String Pass)
     {
         if(Email==null || Pass==null)
         {
             JOptionPane.showMessageDialog(null,"Email And Pass null","Sorry!",JOptionPane.ERROR_MESSAGE);
         }
         else
         {
             String user = Email;
             prerfEmployee.put("Email",Email);
             String pass = Pass;
             prerfEmployee.put("Password",pass);
              System.out.println("Data disimpan");
             
         }
     }
     public final void checked(boolean remember)
     {
         if(remember==true)
         {
             saveemailpass(txt_emp_id.getText(),txt_password_emp.getText());
         }
         else
         {
             System.out.println("Null karakter");
         }
     }
     
     
    public void ChangeColor(JPanel hover, Color random)
    {
        hover.setBackground(random);
    }

            //    Start close color
    public void setColor(JPanel p)
    {
        p.setBackground(new Color(0,0,55));
        
    }
    
    public void resetColor(JPanel p1)
    {
        p1.setBackground(new Color(211, 219, 226));
    }
             //    end close color
    
    
    
     public void setColorlogin(JPanel p)
    {
        p.setBackground(new Color(255,255,255));
       
    }
    
    public void resetColorlogin(JPanel p1)
    {
        p1.setBackground(new Color(5,10,46));
        
    }
    
    //    Start admin color
    public void setColorsigin(JPanel p) {
        p.setBackground(new Color(5,10,46));

    }

    public void resetColorsigin(JPanel p1) {
        p1.setBackground(new Color(0,51,51));

    }
    
    public void clickMenuRight(JPanel h1, JPanel h2,JPanel h3,int num)
    {
        if(num==1)
        {
            h1.setBackground(new Color (0,60,60)); //25,29,74
            h2.setBackground(new Color (5,10,46)); //25,29,74
            h3.setBackground(new Color (5,10,46)); //25,29,74
        }
        if(num==2)
        {
//            h1.setBackground(new Color (5,10,46)); //25,29,74
//            h2.setBackground(new Color (0,60,60)); //25,29,74
            h1.setBackground(new Color (0,60,60)); //25,29,74
            h2.setBackground(new Color (5,10,46)); //25,29,74
            h3.setBackground(new Color (5,10,46)); //25,29,74
        }
        
        if(num==3)
        {
            h1.setBackground(new Color (0,60,60)); //25,29,74
            h2.setBackground(new Color (5,10,46)); //25,29,74
            h3.setBackground(new Color (5,10,46)); //25,29,74
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        login_here_emp1 = new javax.swing.JLabel();
        panel_signin_emp = new javax.swing.JPanel();
        label_signin_emp = new javax.swing.JLabel();
        CboxShowPass_emp = new javax.swing.JCheckBox();
        CboxRememPassEmployee = new javax.swing.JCheckBox();
        txt_password_emp = new javax.swing.JPasswordField();
        txt_emp_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(5, 10, 46));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_here_emp1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        login_here_emp1.setForeground(new java.awt.Color(153, 153, 153));
        login_here_emp1.setText("Login Here");
        jPanel4.add(login_here_emp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, -1, -1));

        panel_signin_emp.setBackground(new java.awt.Color(5, 10, 46));
        panel_signin_emp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        panel_signin_emp.setPreferredSize(new java.awt.Dimension(130, 40));
        panel_signin_emp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_signin_emp.setBackground(new java.awt.Color(5, 10, 46));
        label_signin_emp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        label_signin_emp.setForeground(new java.awt.Color(204, 204, 255));
        label_signin_emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signin_emp.setText("SignIn");
        label_signin_emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_signin_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_signin_empMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_signin_empMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_signin_empMouseExited(evt);
            }
        });
        panel_signin_emp.add(label_signin_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 250, 38));

        jPanel4.add(panel_signin_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, -1));

        CboxShowPass_emp.setBackground(new java.awt.Color(5, 10, 46));
        CboxShowPass_emp.setForeground(new java.awt.Color(255, 255, 255));
        CboxShowPass_emp.setText("show");
        CboxShowPass_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxShowPass_empActionPerformed(evt);
            }
        });
        jPanel4.add(CboxShowPass_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        CboxRememPassEmployee.setBackground(new java.awt.Color(5, 10, 46));
        CboxRememPassEmployee.setForeground(new java.awt.Color(255, 255, 255));
        CboxRememPassEmployee.setText("kepp me");
        jPanel4.add(CboxRememPassEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        txt_password_emp.setBackground(new java.awt.Color(5, 10, 46));
        txt_password_emp.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txt_password_emp.setForeground(new java.awt.Color(255, 255, 255));
        txt_password_emp.setText("**********");
        txt_password_emp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_password_emp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_password_empFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_password_empFocusLost(evt);
            }
        });
        jPanel4.add(txt_password_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 40));

        txt_emp_id.setBackground(new java.awt.Color(5, 10, 46));
        txt_emp_id.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        txt_emp_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_emp_id.setText("Employee Id");
        txt_emp_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_emp_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emp_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emp_idFocusLost(evt);
            }
        });
        jPanel4.add(txt_emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 40));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_password_empFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_empFocusGained
        if (txt_password_emp.getText().equals("**********")) {
            txt_password_emp.setText("");
            txt_password_emp.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_password_empFocusGained

    private void txt_password_empFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password_empFocusLost
        if (txt_password_emp.getText().equals("")) {
            txt_password_emp.setText("**********");
            txt_password_emp.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_password_empFocusLost

    private void txt_emp_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_idFocusGained
        if (txt_emp_id.getText().equals("Employee Id")) {
            txt_emp_id.setText("");
            txt_emp_id.setForeground(new Color(255,255,255));

        }
    }//GEN-LAST:event_txt_emp_idFocusGained

    private void txt_emp_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emp_idFocusLost
        if (txt_emp_id.getText().equals("")) {
            txt_emp_id.setText("Employee Id");
            txt_emp_id.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_emp_idFocusLost

    private void label_signin_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_signin_empMouseClicked

//        int flag = 1;
//        if (txt_emp_id.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(null, "Please Write Username !","Sorry!",JOptionPane.ERROR_MESSAGE);
//        } else if (txt_password_emp.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Please Write Password !","Sorry!",JOptionPane.ERROR_MESSAGE);
//        } else {
//            try {
//
//                String Driver = "com.mysql.jdbc.Driver";
//                String URL = "jdbc:mysql://localhost:3306/medical";
//                Class.forName(Driver);
//                Connection Conn = DriverManager.getConnection(URL, "root", "");
//                Statement S = Conn.createStatement();
//                ResultSet RS = S.executeQuery(
//                    "SELECT * FROM employee_login where Employee_Id ='" + txt_emp_id.getText()
//                    + "' and Password ='" + txt_password_emp.getText() + "'");
//
//                while (RS.next()) {
//                    String user = RS.getString("Employee_Id");
//                    String pass = RS.getString("Password");
//                    if (user.equals(txt_emp_id.getText()) & pass.equals(txt_password_emp.getText())) {
//                        flag = 0;
//                        break;
//                    }
//                }
//                if (flag == 0) {
//
//                    if (CboxRememPassEmployee.isSelected()) {
//                        checked(true);
//
//                    } else {
//                        checked(false);
//
//                    }
//                    //dispose();
//                    new employee_panel1().setVisible(false);
//                    new employee_panel1().setVisible(true);
//                    new NoticeWindow(NoticeType.SUCCESS_NOTIFICATION,"Congratulations!", NoticeWindow.SHORT_DELAY, NPosition.CENTER);
//                    //panel_employee_log.setVisible(false);
//                    //
//
//                } else {
//
//                    //JOptionPane.showMessageDialog(null, "Invalid Username and Password","Sorry!",JOptionPane.ERROR_MESSAGE);
//                    NoticeWindow noticeWindow = new NoticeWindow(NoticeType.ERROR_NOTIFICATION, "Sorry! Invalid Username and Password", NoticeWindow.SHORT_DELAY, NPosition.CENTER);
//                }
//
//            } catch (Exception e) {
//
//                JOptionPane.showMessageDialog(null, e);
//            }
//        }





        int flag = 1;
        if (txt_emp_id.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Write Username !", "Sorry!", JOptionPane.ERROR_MESSAGE);
        } else if (txt_password_emp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Write Password !", "Sorry!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                String Driver = "com.mysql.jdbc.Driver";
                String URL = "jdbc:mysql://localhost:3306/medical";
                Class.forName(Driver);
                Connection Conn = DriverManager.getConnection(URL, "root", "");
                java.sql.Statement S = Conn.createStatement();
                ResultSet RS = S.executeQuery(
                        "SELECT * FROM employee_login where Employee_Id ='" + txt_emp_id.getText()
                        + "' and Password ='" + txt_password_emp.getText() + "'");

                while (RS.next()) {
                    String user = RS.getString("Employee_Id");
                    String pass = RS.getString("Password");
                    if (user.equals(txt_emp_id.getText()) & pass.equals(txt_password_emp.getText())) {
                        flag = 0;
                        break;
                    }
                }
                if (flag == 0) {

                    if (CboxRememPassEmployee.isSelected()) {
                        checked(true);

                    } else {
                        checked(false);

                    }                  
                    new NoticeWindow(NoticeType.SUCCESS_NOTIFICATION,"Congratulations!", NoticeWindow.SHORT_DELAY, NPosition.CENTER);

                        JOptionPane.showMessageDialog(null, "Login Success");

                    } else {

                       NoticeWindow noticeWindow = new NoticeWindow(NoticeType.ERROR_NOTIFICATION, "Sorry! Invalid Username and Password", NoticeWindow.SHORT_DELAY, NPosition.CENTER);                

                    }
                }

             catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_label_signin_empMouseClicked

    private void label_signin_empMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_signin_empMouseEntered
        setColorsigin(panel_signin_emp);
        label_signin_emp.setForeground(new Color(0,204,204));
    }//GEN-LAST:event_label_signin_empMouseEntered

    private void label_signin_empMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_signin_empMouseExited
        resetColorsigin(panel_signin_emp);
        label_signin_emp.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_label_signin_empMouseExited

    private void CboxShowPass_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxShowPass_empActionPerformed
        if (CboxShowPass_emp.isSelected()) {
            txt_password_emp.setEchoChar((char) 0); //password = JPasswordField
        } else {
            txt_password_emp.setEchoChar('*');
        }
    }//GEN-LAST:event_CboxShowPass_empActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CboxRememPassEmployee;
    private javax.swing.JCheckBox CboxShowPass_emp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_signin_emp;
    private javax.swing.JLabel login_here_emp1;
    private javax.swing.JPanel panel_signin_emp;
    private javax.swing.JTextField txt_emp_id;
    private javax.swing.JPasswordField txt_password_emp;
    // End of variables declaration//GEN-END:variables
}
