/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.swing.JOptionPane;

/**
 *
 * @author h
 */
public class Patient_Billing extends javax.swing.JFrame {

    /**
     * Creates new form Patient_Receipt
     */
    public Patient_Billing() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        patient_id.requestFocus();

        txt_patient_full_name.setEditable(false);

        txt_patient_father_name.setEditable(false);

        txt_patient_age.setEditable(false);

        txt_patient_gen.setEditable(false);

        txt_patient_contact.setEditable(false);

        txt_patient_reg_date.setEditable(false);
        txt_patient_doctor_name.setEditable(false);

        txt_patient_address.setEditable(false);

        txt_patient_doctor_name.setEditable(false);

        txt_patient_illness.setEditable(false);

    }

    public void Billing() {
        String search = patient_id.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/medical", "root", "");
            Statement st = (Statement) con.createStatement();
            String query = "select *from patient_receipt where Patient_Id='" + search + "'";
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {

                String s1 = rs.getString("Patient_Id"); //Full NAme
                patient_id.setText(s1);

                String s2 = rs.getString("Full_Name"); //Full NAme
                txt_patient_full_name.setText(s2);

                String s3 = rs.getString("Father_Name"); //F Name
                txt_patient_father_name.setText(s3);

                String s4 = rs.getString("Age"); //Mother Name
                txt_patient_age.setText(s4);

                String s5 = rs.getString("Gender"); //Mother Name
                txt_patient_gen.setText(s5);

                String s6 = rs.getString("Contact"); //Mother Name
                txt_patient_contact.setText(s6);

                String s7 = rs.getString("Doctor_Name"); //status
                txt_patient_doctor_name.setText(s7);

                String s8 = rs.getString("Address"); //status
                txt_patient_address.setText(s8);

                String s9 = rs.getString("Registration_Date"); //status
                txt_patient_reg_date.setText(s9);

                String s10 = rs.getString("Patient_illness"); //status
                txt_patient_illness.setText(s10);

                Error_Id.setText("*Id match");
                Error_Id.setForeground(Color.GREEN);

            } else {

                Error_Id.setVisible(true);
                Error_Id.setText("*Sorry! Id doesn't match");
            }

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ticket_profile = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_patient_full_name = new javax.swing.JTextField();
        txt_patient_father_name = new javax.swing.JTextField();
        txt_patient_gen = new javax.swing.JTextField();
        txt_patient_reg_date = new javax.swing.JTextField();
        txt_patient_age = new javax.swing.JTextField();
        txt_patient_contact = new javax.swing.JTextField();
        txt_patient_illness = new javax.swing.JTextField();
        txt_patient_doctor_name = new javax.swing.JTextField();
        txt_patient_address = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt_visit_bill = new javax.swing.JTextField();
        txt_test_bill = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_bill_result = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        patient_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Error_Id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticket_profile.setBackground(new java.awt.Color(46, 64, 83));
        ticket_profile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        ticket_profile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ticket_profileComponentShown(evt);
            }
        });
        ticket_profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(33, 47, 61));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 182, 191));
        jLabel1.setText("Patient Billing");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 239, 40));

        ticket_profile.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 986, 45));

        jPanel2.setBackground(new java.awt.Color(46, 64, 83));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_patient_full_name.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_full_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_full_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_full_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_patient_full_name.setText("Full Name");
        txt_patient_full_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_full_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_full_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_full_nameFocusLost(evt);
            }
        });
        txt_patient_full_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_patient_full_nameKeyReleased(evt);
            }
        });
        jPanel2.add(txt_patient_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 36));

        txt_patient_father_name.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_father_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_father_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_father_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_patient_father_name.setText("Father Name");
        txt_patient_father_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_father_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_father_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_father_nameFocusLost(evt);
            }
        });
        txt_patient_father_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_patient_father_nameKeyReleased(evt);
            }
        });
        jPanel2.add(txt_patient_father_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, 36));

        txt_patient_gen.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_gen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_gen.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_gen.setText("Gender");
        txt_patient_gen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_gen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_genFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_genFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 170, 36));

        txt_patient_reg_date.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_reg_date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_reg_date.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_reg_date.setText("Registration Date");
        txt_patient_reg_date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_reg_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_reg_dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_reg_dateFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_reg_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 170, 36));

        txt_patient_age.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_age.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_age.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_age.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_patient_age.setText("Age");
        txt_patient_age.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_ageFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 130, 36));

        txt_patient_contact.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_contact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_contact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_patient_contact.setText("Contact");
        txt_patient_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_contactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_contactFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 180, 36));

        txt_patient_illness.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_illness.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_illness.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_illness.setText("Patient Illness");
        txt_patient_illness.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_illness.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_illnessFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_illnessFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_illness, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 170, 36));

        txt_patient_doctor_name.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_doctor_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_doctor_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_doctor_name.setText("Doctor Name");
        txt_patient_doctor_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_doctor_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_doctor_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_doctor_nameFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_doctor_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 180, 36));

        txt_patient_address.setBackground(new java.awt.Color(46, 64, 83));
        txt_patient_address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_patient_address.setForeground(new java.awt.Color(255, 255, 255));
        txt_patient_address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_patient_address.setText("Address");
        txt_patient_address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_patient_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patient_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patient_addressFocusLost(evt);
            }
        });
        jPanel2.add(txt_patient_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 36));

        ticket_profile.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 970, 170));

        jPanel4.setBackground(new java.awt.Color(46, 64, 83));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(46, 64, 83));
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 150, 40));

        jButton1.setBackground(new java.awt.Color(46, 64, 83));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/close button.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 150, 40));

        jPanel6.setBackground(new java.awt.Color(46, 64, 83));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_visit_bill.setBackground(new java.awt.Color(46, 64, 83));
        txt_visit_bill.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txt_visit_bill.setForeground(new java.awt.Color(255, 255, 255));
        txt_visit_bill.setText("Doctor Visit Bill");
        txt_visit_bill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_visit_billFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_visit_billFocusLost(evt);
            }
        });
        jPanel6.add(txt_visit_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 40));

        txt_test_bill.setBackground(new java.awt.Color(46, 64, 83));
        txt_test_bill.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        txt_test_bill.setForeground(new java.awt.Color(255, 255, 255));
        txt_test_bill.setText("Test Bill");
        txt_test_bill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_test_billFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_test_billFocusLost(evt);
            }
        });
        jPanel6.add(txt_test_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 40));

        jPanel8.setBackground(new java.awt.Color(33, 47, 61));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(174, 182, 191));
        jLabel4.setText(" Billing");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 317, 30));

        txt_bill_result.setBackground(new java.awt.Color(46, 64, 83));
        txt_bill_result.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_bill_result.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(txt_bill_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, 40));

        jButton3.setBackground(new java.awt.Color(46, 64, 83));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("save");
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 70, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 320, 330));

        jPanel7.setBackground(new java.awt.Color(46, 64, 83));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(46, 64, 83));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Doctor Visit", "Test Fee", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 330));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 330));

        ticket_profile.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 970, 350));

        jPanel5.setBackground(new java.awt.Color(33, 47, 61));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employee/search icon.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 40));

        patient_id.setBackground(new java.awt.Color(46, 64, 83));
        patient_id.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        patient_id.setForeground(new java.awt.Color(204, 204, 255));
        patient_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patient_idKeyReleased(evt);
            }
        });
        jPanel5.add(patient_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, 35));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Id");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        ticket_profile.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 270, 55));

        Error_Id.setForeground(new java.awt.Color(0, 255, 153));
        Error_Id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ticket_profile.add(Error_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 180, 20));

        jPanel1.add(ticket_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 684));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 684));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_patient_full_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_full_nameFocusGained
        if (txt_patient_full_name.getText().equals("Full Name")) {
            txt_patient_full_name.setText("");
            txt_patient_full_name.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_full_nameFocusGained

    private void txt_patient_full_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_full_nameFocusLost
        if (txt_patient_full_name.getText().equals("")) {
            txt_patient_full_name.setText("Full Name");
            txt_patient_full_name.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_full_nameFocusLost

    private void txt_patient_full_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_patient_full_nameKeyReleased

        //txtSubject.setText(txt_patient_full_name.getText());
    }//GEN-LAST:event_txt_patient_full_nameKeyReleased

    private void txt_patient_father_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_father_nameFocusGained
        if (txt_patient_father_name.getText().equals("Father Name")) {
            txt_patient_father_name.setText("");
            txt_patient_father_name.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_father_nameFocusGained

    private void txt_patient_father_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_father_nameFocusLost
        if (txt_patient_father_name.getText().equals("")) {
            txt_patient_father_name.setText("Father Name");
            txt_patient_father_name.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_father_nameFocusLost

    private void txt_patient_father_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_patient_father_nameKeyReleased

    }//GEN-LAST:event_txt_patient_father_nameKeyReleased

    private void txt_patient_contactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_contactFocusGained
        if (txt_patient_contact.getText().equals("Contact")) {
            txt_patient_contact.setText("");
            txt_patient_contact.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_contactFocusGained

    private void txt_patient_contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_contactFocusLost
        if (txt_patient_contact.getText().equals("")) {
            txt_patient_contact.setText("Contact");
            txt_patient_contact.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_contactFocusLost

    private void txt_patient_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_addressFocusGained
        if (txt_patient_address.getText().equals("Address")) {
            txt_patient_address.setText("");
            txt_patient_address.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_addressFocusGained

    private void txt_patient_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_addressFocusLost
        if (txt_patient_address.getText().equals("")) {
            txt_patient_address.setText("Address");
            txt_patient_address.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_addressFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new Patient_Billing().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ticket_profileComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ticket_profileComponentShown

    }//GEN-LAST:event_ticket_profileComponentShown

    private void patient_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patient_idKeyReleased
        Billing();
    }//GEN-LAST:event_patient_idKeyReleased

    private void txt_patient_genFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_genFocusGained
        if (txt_patient_gen.getText().equals("Gender")) {
            txt_patient_gen.setText("");
            txt_patient_gen.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_genFocusGained

    private void txt_patient_genFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_genFocusLost
        if (txt_patient_gen.getText().equals("")) {
            txt_patient_gen.setText("Gender");
            txt_patient_gen.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_genFocusLost

    private void txt_patient_reg_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_reg_dateFocusGained
        if (txt_patient_reg_date.getText().equals("Registration Date")) {
            txt_patient_reg_date.setText("");
            txt_patient_reg_date.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_reg_dateFocusGained

    private void txt_patient_reg_dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_reg_dateFocusLost
        if (txt_patient_reg_date.getText().equals("")) {
            txt_patient_reg_date.setText("Registration Date");
            txt_patient_reg_date.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_reg_dateFocusLost

    private void txt_patient_ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_ageFocusGained
        if (txt_patient_age.getText().equals("Age")) {
            txt_patient_age.setText("");
            txt_patient_age.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_ageFocusGained

    private void txt_patient_ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_ageFocusLost
        if (txt_patient_age.getText().equals("")) {
            txt_patient_age.setText("Age");
            txt_patient_age.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_ageFocusLost

    private void txt_patient_doctor_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_doctor_nameFocusGained
        if (txt_patient_doctor_name.getText().equals("Doctor Name")) {
            txt_patient_doctor_name.setText("");
            txt_patient_doctor_name.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_doctor_nameFocusGained

    private void txt_patient_doctor_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_doctor_nameFocusLost

        if (txt_patient_doctor_name.getText().equals("")) {
            txt_patient_doctor_name.setText("Doctor Name");
            txt_patient_doctor_name.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_doctor_nameFocusLost

    private void txt_patient_illnessFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_illnessFocusGained
        if (txt_patient_illness.getText().equals("Patient Illness")) {
            txt_patient_illness.setText("");
            txt_patient_illness.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_illnessFocusGained

    private void txt_patient_illnessFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patient_illnessFocusLost
        if (txt_patient_illness.getText().equals("")) {
            txt_patient_illness.setText("Patient Illness");
            txt_patient_illness.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_patient_illnessFocusLost

    private void txt_visit_billFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_visit_billFocusGained
        if (txt_visit_bill.getText().equals("Doctor Visit Bill")) {
            txt_visit_bill.setText("");
            txt_visit_bill.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_visit_billFocusGained

    private void txt_visit_billFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_visit_billFocusLost
         if (txt_visit_bill.getText().equals("")) {
            txt_visit_bill.setText("Doctor Visit Bill");
            txt_visit_bill.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_visit_billFocusLost

    private void txt_test_billFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_test_billFocusGained
        if (txt_test_bill.getText().equals("Test Bill")) {
            txt_test_bill.setText("");
            txt_test_bill.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_test_billFocusGained

    private void txt_test_billFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_test_billFocusLost
       if (txt_test_bill.getText().equals("")) {
            txt_test_bill.setText("Test Bill");
            txt_test_bill.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_txt_test_billFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error_Id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField patient_id;
    private javax.swing.JPanel ticket_profile;
    private javax.swing.JTextField txt_bill_result;
    private javax.swing.JTextField txt_patient_address;
    private javax.swing.JTextField txt_patient_age;
    private javax.swing.JTextField txt_patient_contact;
    private javax.swing.JTextField txt_patient_doctor_name;
    private javax.swing.JTextField txt_patient_father_name;
    private javax.swing.JTextField txt_patient_full_name;
    private javax.swing.JTextField txt_patient_gen;
    private javax.swing.JTextField txt_patient_illness;
    private javax.swing.JTextField txt_patient_reg_date;
    private javax.swing.JTextField txt_test_bill;
    private javax.swing.JTextField txt_visit_bill;
    // End of variables declaration//GEN-END:variables
}
